services:
  lumi-webapp:
    image: fuck:latest
    ports:
      - "4545:4545"
    environment:
      - NODE_ENV=production
      - PORT=4545
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    container_name: lumi-webapp

    networks:
      - lumi-network

networks:
  lumi-network:
    driver: bridge