// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPIahGtokJTGxDMV78rfgAPBigOJbqoHk',
    appId: '1:853491388305:web:1558aec290ba9b14479430',
    messagingSenderId: '853491388305',
    projectId: 'lumi-app-29c94',
    storageBucket: 'lumi-app-29c94.firebasestorage.app',
    authDomain: 'lumi-app-29c94.firebaseapp.com',
    measurementId: 'G-7K9DZ0K5EB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVKKWY4dRzT3yV4lDagxTeB1CtFb8yN2A',
    appId: '1:853491388305:android:f0f65f2cfd80c41e479430',
    messagingSenderId: '853491388305',
    projectId: 'lumi-app-29c94',
    storageBucket: 'lumi-app-29c94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlcOD8AcLyCHcDW2FYmoieaY5_KQoocDw',
    appId: '1:853491388305:ios:ebacd14a60b7b97b479430',
    messagingSenderId: '853491388305',
    projectId: 'lumi-app-29c94',
    storageBucket: 'lumi-app-29c94.firebasestorage.app',
    iosBundleId: 'uz.lumipass.mobile',
  );

}